version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8081:8081"
      - "443:443"
      - "80:80"
    restart: always
    privileged: true
    networks:
      - net-default
    volumes:
      - /stack:/stack
      - ./nginx/conf.d:/etc/nginx/conf.d
  phpfpm:
    container_name: phpfpm
    image: tiredoy/php7.3:1.0
#    build: ./php
    ports:
      - "9000:9000"
      - "9501:9501"
    volumes:
      - /stack:/stack
      - ./phpfpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    privileged: true
    networks:
      - net-default
  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=guke@8888
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/datadir:/var/lib/mysql
    restart: always
    privileged: true
    networks:
      - net-default
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    networks:
      - net-default
  mongo:
    container_name: mongo
    image: mongo:4.0.4
    ports:
      - "27017:27017"
    networks:
      - net-default

networks:
  net-default:
